language: node_js
node_js:
- '7'
before_script:
- npm install -g npm@'>=3'
deploy:
  provider: npm
  email: divyansh.yadav@gmail.com
  api_key:
    secure: mg0bAIoxugNl7xHolaSE3oS+NSqgD0HoDvwFzDRaSTODa2uSrbvUB/yha24uNZQ7O9SdJV7PCPBQYxEjGGADG2zd0bI3YvKF0VmNJitkTcFOWzWLUskFJ+Mse8VCw4OaRpZLPcKBmxbOPCh/iQTQZHgsNSBeeDbQ3n6gBlif+FYpOVWjxhAx56AUdvgHhY+yvs9BuIask+ixjhdt0KPjap0JEkkO3U53DK0KDbemfncu5oDTZvmJ+v7aSTAPVG09UKPq1c8mE8UXsb3zF2/fKwV1cQzuI/CnE3qyfaO93w6XMSw3HdHpHYxjLcFTtJm4H9EjiIVgAuxPo6d6lCoGKxJwqZDsI0gqLiOgaSIHQ2mKeoZ+iynpHDem00qoVnosSTlTyM15EQ+eYMlfBSDkcLt0XfnePEUkTVPZQQpRBrK6ioFKrjo27M5OLcZ/ai92gnC2wCWRxWq3qUrlhG3grrdU4QeB4398Mx7rN/UAJcIwF+4uI+/pk/nydI6yC85oHu/VK6wHdMjAQKViUh1e0ijmiKkJvi/U2InnZWRhCP+fuNXFwOx0Lh5nhbf7Gg+t8mRWnnhtp5IY40pQoNGv9yA4UkAowmc47iTV7+INoQF6ohtxc+oDu7D4F5gN9k+2KFDCWsThTFnCfvzSTgg03GNJeapFzNp5RKhyW/mvvFc=
  skip_cleanup: true
  on:
    tags: true
    repo: divyanshyadav/data-structures-again
