language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: divyansh.yadav@gmail.com
  api_key:
    secure: DRuT4vqtvEHC2HTSt2maXhm3cqwn84Bo5unslXFlTxuhK+efki9iAFRhkTLB15WDGLqVfflVYA7bonq8aUDspU2G9Z3C0PC1NOJf4tMAq93TetslBLWmhul/p5vucUyf2QIlAptyt+gr0Wapkr1viZpC6S4DnHy+v66XDRBSeH8SpXtmbdV2WMtwL0uLK2I2sbBR9T99JzUG9whtTiW9fVRd1YL/yKPEnirhGv8hYtBVbV+9JDM7iZrxlFPCEf5ID2IQVutT7wNqBIaBCd80psfT1CwChiai0m6cwu3f+dNRCe9Aw1F/knfsMw8UAPbGGpIuG4n5xW7SGatFgUWHmt88zbbdARwornXT4WeTViwcYcUpgE2/FEVJwoc8ELiunlDVU6DFGpuKZMb4jjzgNEEQoaHvDeTLYJn8LbG8KoYfmhV/G8mEru4u7RIb0Clcr+Py5rJnNoFzdUGykIQz5Ut430th8xLV9mZZBRBwiIuTUxIlSOhDztqXxk1GqAb7tWQvQYuuqjg7pb8toqwdPY7YikJ/hH/v61QyGGFaJxeCsmkzBeah+rH92pD0gcXjkXd1bM4xjSqUVYpf7DyrbKTvN3R0OGLMNExOwmPPEl2OPl3l3aiTEvUynQdbja/fteGQOkspWuQzZVK1cwrlVwXUpgm4ZJiMU3BCVv4HxHs=
  on:
    tags: true
    repo: divyanshyadav/data-structures-again
