language: node_js
node_js:
- '11'
script:
- npm test
- npm run coveralls
deploy:
  provider: npm
  email: divyansh.yadav@gmail.com
  api_key:
    secure: C2HYIiZ4TAxEg4Mv2VYGKt9dsSlW3PfaiafFHyHh/qEBv71ZQCHBcNf9Oi1dFZri9B2/iyFsFTVYqKFIVoTF8ptCcyx+IQypAtq4tIlJIUeu+Lm6HO+P57hzSxl+oNTVrhnLo+lpCa7I+DQ7x2L8cmQSCa1sDQ97Mm2Ou23njKn+xZKto7vRzmjbZmxBbjndv3+VfL0nAVUETBm+5qc09McVxunPdGkqD5rl4hzRq55t93gPbfaLxl/oydenSXgHNHEi+nZLOt4IBnR3l3waXJkC4tI0Tx1SmK6hGt++nvDojBE/HbsGB4HhZKakmh+2xOJ1qTcKdfsLIlGUJ91ZXxkbcT11XQqzYmLSc41zWB/szUQ7nZIhXB8EPorLCj57iqluRS3LLkYFmikdkE7/l8jneokZvDiZSs9zkUpqS7Lxi7MkzxJYM+aNG9hsfVWAfNTdqI4hozcjDbhTpVSH7TWy6PrCYa2W8YvOnXj482oDVpBAbUhQItaNNCHQKJvX6UZFethX5TrAkzjFmN/KT6yArydXdP02NtQsJbegLBJSF2aTGhJWaXZNMIYAtVe6O+brl5uUMy5hA8CKrRq8as8R8USOUHxaWHGoLwDhYrRwKSWrGp+trQnGMdoP46sqMNtZrHQ6Rsm1HU5Y8n1I4yd9kAtmkyzmhUXD1Hzzauk=
  skip_cleanup: true
  on:
    tags: true
    repo: divyanshyadav/data-structures-again
